### ISSUE TITLE
Deprecate/remove Promise

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#107]
Now that node 4.0.0 is out, it means we are currently supportly three different versions of Node. It would be nice to just target that previous 2 releases. Considering that, I propose we remove http://npm.im/promise and use the native Promise.

**Comment by tunnckoCore** [comment]
:-1: We should stay with it until April 2017, I understood correctly, when 0.10 will be totally obsoleted. That's why I changed my boilerplate travis file for builds to support only 0.10, 0.12 and 4.

**Comment by ForbesLindesay** [comment]
I agree with @tunnckoCore.  This is definitely something we want to do, but I think this is about 6 months too early.

**Comment by RobLoach** [comment]
Node 6 is out now, and it has been more than 6 months. Support only Node.js 4, 5, and 6?

**Comment by TimothyGu** [comment]
We at @pugjs are using jstransformers for Pug 2.0.0, which supports everything from 0.10. It'd be a shame to see a module we use not support the Node.js versions Pug supports, especially when the support requires literally one line of code.

**Comment by tunnckoCore** [comment]
> It'd be a shame to see a module we use not support the Node.js versions Pug supports

:+1:

**Comment by RobLoach** [comment]
What is your support window? Will it align with [Node.js's LTS schedule](https://github.com/nodejs/LTS#lts-schedule)?

**Comment by RobLoach** [comment]
We're no longer supporting Node.js 0.10. Node.js 0.12 has native `Promise` support. We can now safely remove http://npm.im/promise .
