### ISSUE TITLE
vel

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#112]
https://github.com/yoshuawuyts/vel

I'm not completely sure about the testing, how can be done.

**Comment by tunnckoCore** [comment]
It would be tricky to implement all (more than one) things. e.g.

```js
const el = vel(function (h, state) {
  return h('div', state.foo)
})
```
and
```js
const el = vel(function (h) {
  return h.html('<div>hello world</div>')
})
```
and etc.

**Comment by webketje** [comment]
Project looks abandoned: last release and significant activity 7 years ago
