### ISSUE TITLE
Command Line Interface `jstransformer-cli`

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#13]
@tunnckoCore brought this up in https://github.com/jstransformers/meta/issues/2 .

I believe a large chunk of these tools will be handled by https://github.com/jstransformers/nuke or whatever we end up adding in there.

**Comment by ForbesLindesay** [comment]
I was intending to have a tool called `jstransformer-cli` but not for that purpose.  I was thinking that users could use it as a cli for building files using jstransformers.  i.e. they could do something like:

```
npm install -g jstransformer-cli
jstransformer install jade
jstransformer render jade input.jade --locals '{foo: "bar"}' > output.html
jstransformer compile jade input.jade > output.js
```

where the "render" command maps roughly to the render/renderFile methods and "compile" maps roughly to compileClient/compileFileClient.  It could handle all the relevant things regarding watching of files etc.  It could even potentially have some kind of `serve` mode that gives you a basic static file server.

**Comment by RobLoach** [comment]
> I was intending to have a tool called jstransformer-cli but not for that purpose. I was thinking that users could use it as a cli for building files using jstransformers. i.e. they could do something like

:+1: I could see that pattern being used through Grunt/Gulp plugins as well, alongside  `transformer-cli`.

> It could even potentially have some kind of `serve` mode that gives you a basic static file server.

Might be nice to off-load some of that work to other utilities to keep `transformer-cli` small, focused, and minimalistic as possible. Remember the first two rules of [Mike Gancarz's UNIX Philosophy](http://en.wikipedia.org/wiki/Unix_philosophy#Mike_Gancarz:_The_UNIX_Philosophy) :wink: 
* Small is beautiful
* Make each program do one thing well

**Comment by tunnckoCore** [comment]
>  I was thinking that users could use it as a cli for building files using jstransformers. i.e. they could do something like:

exactly.

**Comment by tunnckoCore** [comment]
@ForbesLindesay hm.. looks good. Can I start it?

> where the "render" command maps roughly to the render/renderFile methods

and `jstransformer install jade` means "install jstransformer-jade and use it"?

**Comment by ForbesLindesay** [comment]
Yes, feel free to get started :+1: 

Yes, `jstransformer install jade` would install `jstransformer-jade`.  I'm not sure exactly what the ideal location to install it would be.  Probably just run `npm i jstransformer-jade --save` in current working directory.  It might not be a worthwhile shortcut yet.

**Comment by tunnckoCore** [comment]
> Yes, feel free to get started 

Cool, thanks.

> in current working directory.

hm. I think it should be in the `jstransformer-cli` directory, b/c just the cli would use it.

> Probably just run npm i jstransformer-jade --save in

its not needed to be anywhere. Have some use case in my mind: you are user, you just have fresh system, `node` and `jstransformer-cli` and just want to render/compile some source/file. Its not needed to be installed in current working directory even saved in package.json, because if you want to use it like that you should use just `jstransformer`, not the cli.

**Comment by ForbesLindesay** [comment]
I guess it depends a bit on where jstranformer-cli is installed and the project you're currently working on.  The thing I want to try and get right is that if you make a project that uses jstransformer-cli in a build script, you should be able to specify everything in your package.json correctly such that I can just do `npm install && npm run build` in to install and build your repo.  e.g. if you had:

```json
{
  "dependencies": {
    "jstransformer": "*",
    "jstransformer-jade": "*"
  },
  "scripts": {
    "build": "jstransformer render jade input.jade > output.html"
  }
}
```

**Comment by tunnckoCore** [comment]
Yea, gotcha. And it still be done only just in the `jstransformer-cli` directory and save to his package.json.

**Comment by tunnckoCore** [comment]
> on where jstranformer-cli is installed

mm nope, there's no matter where it is installed, if his renderers is installed in his directory.

**Comment by RobLoach** [comment]
Also saw [`lazy-require`](https://www.npmjs.com/package/lazy-require) pop up a little while ago. Might be interesting to lazy-load the transformers. While the design is questionable, it would allow using `jstransformer-jade` without explicitly requireing it in *package.json*.

``` javascript
$transform = require('lazy-require')($transformName);
process.stdout($transform.renderFile($file));
```

Not sure if this was asked before, but will this live in a seperate `jstransformer-cli` package? http://github.com/jstransformers/jstransformer-cli ?

**Comment by tunnckoCore** [comment]
> Not sure if this was asked before, but will this live in a seperate jstransformer-cli package?

I guess, yes.

Because if, say, you have `my-awesome-pkg` project/directory and you want to use it like you show in `scripts`. You probably should run 

```
npm i --save jstransformer-cli
jstransformer install jade
```
and whats going on here? it installs only `jstransformer-cli` in the `my-awesome-pkg` directory. then for every `jstransformer install` it should install his transformers in `jstransformer-cli` directory, not in project directory. And there won't have need to add them to the package.json of the `my-awesome-pkg` project.

**Comment by tunnckoCore** [comment]
>  Might be interesting to lazy-load the transformers. 

SG2M

**Comment by ForbesLindesay** [comment]
Yes, this should definitely live in a separate jstransformer-cli package.

lazy-require is an interesting idea.  The main downside is that you don't have any ability to specify the versions that should be used.

@tunnckoCore The problem with not putting anything in package.json is that when someone else clones that repo onto another machine, they have to repeat the process for running jstransformer install for each dependency.

**Comment by tunnckoCore** [comment]
hmm, good point, lol

**Comment by tunnckoCore** [comment]
> The main downside is that you don't have any ability to specify the versions that should be used.

not exactly, see https://github.com/bevry/lazy-require/blob/master/src/lib/lazy-require.coffee#L180-L192

**Comment by RobLoach** [comment]
> npm install && npm run build

Now works with...

``` json
{
  "dependencies": {
    "jstransformer-cli": "*",
    "jstransformer-jade": "*"
  },
  "scripts": {
    "build": "jstransformer jade input.jade > output.html"
  }
}
```

**Comment by RobLoach** [comment]
https://github.com/jstransformers/jstransformer-cli

Let's get discussions going on [in the issue queue there](https://github.com/jstransformers/jstransformer-cli/issues). Thanks guys!
