### ISSUE TITLE
Help with `jstransformer-xml2js`, actually async flow

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#14]
wazza :)

`xml2js` have only async, soo.. i should implement only `.renderAsync`, right? But when implement it like

```js
exports.renderAsync = function _renderAsync(str, opts, locals, callback) {
  xml2js.parseString(str, opts, callback);
};
```
then when try it
```js
var transform = require('jstransformer')(require('../index'));
transform.renderAsync(fixture, {}, {}, function(err, res) {
  console.log(err, res)
});
```
or like
```js
var transform = require('jstransformer')(require('../index'));
var promise = transform.renderAsync(fixture);
// throws error to .catch
```
 it throws `[Error: Invalid result object from transform.]` in both cases

**Comment by ForbesLindesay** [comment]
You have to return a Promise from that method

**Comment by tunnckoCore** [comment]
hm.. so it seem it is correctly implemented here https://github.com/jstransformers/jstransformer-xml2js/blob/master/index.js
