### ISSUE TITLE
Add Documentation around what JSTransformers is

### ISSUE THREAD

**Issue by alex-shamshurin** [jstransformers/jstransformer#148]
Why there is no any explanation what is it and for what the purpose it should be used?

**Comment by RobLoach** [comment]
@salex772 Great question. We need some additional documentation around it.

JSTransformers provides an [adapter](https://en.wikipedia.org/wiki/Adapter_pattern) to use many different template engines through the same interface.

**Comment by salex772** [comment]
Good, for example kill what? I see STYLUS adapter for Jade. How it can be used?

**Comment by RobLoach** [comment]
https://github.com/jstransformers/jstransformer/issues/138
