### ISSUE TITLE
support for multiple outputFormat, like inputFormats

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#15]
Also the names of properties.. We need more consistency.

#### Proposal
- `outputFormats` alias to `outputFormat`
- `inputFormats` alias to `inputFormat`
- both to accept only arrays (or plural array, singular only string?)

#### Why?
1. Because libs like [AbsurdJS](https://github.com/jstransformers/jstransformer-absurd) can output css and html, not in same time, but yea. It can transform from JSON/YAML/CSS/JS to CSS/HTML.
2. fast-fingers mistakes, one is plural, other is singular.. nah, not good.

```js
exports.name = 'absurd';
exports.inputFormats = ['absurd', 'absurdjs', 'js', 'json', 'yaml', 'css'];
exports.outputFormats = ['css', 'html'];
```

**Comment by stoeffel** [comment]
> both to accept only arrays (or plural array, singular only string?)

I would accept only strings for singular and plural only arrays.

**Comment by RobLoach** [comment]
I'd actually opt to removing outputFormat entirely.

**Comment by tunnckoCore** [comment]
> I would accept only strings for singular and plural only arrays.

yea, exactly. maybe somthing like this

```js
var outputFormat = this._tr.outputFormat || this._tr.outputFormats;
var inputFormat = this._tr.inputFormat || this._tr.inputFormats || this.name;

outputFormat = Array.isArray(outputFormat) ? outputFormat : [outputFormat];
inputFormat = Array.isArray(inputFormat) ? inputFormat : [inputFormat];

this.outputFormat = this.outputFormats = outputFormat;
this.inputFormat = this.inputFormats = inputFormat;
```

**Comment by tunnckoCore** [comment]
> I'd actually opt to removing outputFormat entirely.

why?

**Comment by RobLoach** [comment]
Remove outputFormat because it makes assumptions on the context of the application. As you demonstrated, the output can be changed based on the options passed to the Tranformer.

I've used [Mustache](https://github.com/jstransformers/jstransformer-mustache) to output CSS before, I've used [ECO](https://github.com/jstransformers/jstransformer-eco) to output JavaScript. There is no way for us to determine what's expected for the output, so we should make no assumption in the matter.

**Comment by stoeffel** [comment]
> There is no way for us to determine what's expected for the output, so we should make no assumption in the matter

true

**Comment by tunnckoCore** [comment]
hmm. good point.

**Comment by tunnckoCore** [comment]
one more use case
https://github.com/jstransformers/jstransformer-gray-matter - what should be inputFormats/outputFormat?

**Comment by tunnckoCore** [comment]
and actually, all template engines or even just mustache-like engines can output just simple text not html

**Comment by tunnckoCore** [comment]
oh, yea, `outputFormat` is json, but what to be the `inputFormats`?

**Comment by ForbesLindesay** [comment]
The purpose of outputFormat is to define a **default** output format for a given transformer.  I.e. If asked to transform a file with a given transformer and told nothing else, what file extension should I use for the output by default.

The purpose of inputFormats is to list the input file extensions that correspond to a given transformer.  I.e. If I'm given a collection of files and a collection of transformers, which transformer should I use for which file.

These use cases should hopefully make it clear that there's not much use in having an array for outputFormat, but it does make sense to have an array of inputFormats
