### ISSUE TITLE
Giphy

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#163]
https://www.npmjs.com/package/giphy-api

**Comment by calebeby** [comment]
Can you explain what this would input and output? Is this even a transpiler?

**Comment by RobLoach** [comment]
Perhaps....

Input: keyword
Output: The image URL

Not sure. Was an idea.

**Comment by calebeby** [comment]
:confused:

**Comment by webketje** [comment]
Vague. There doesn't seem to be any demand for this transformer
