### ISSUE TITLE
SugarML

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#178]
https://github.com/posthtml/sugarml

it is parser/plugin for PostHTML but think it make sense to have it separated too

**Comment by calebeby** [comment]
https://github.com/reshape/sugarml

**Comment by RyanZim** [comment]
@calebeby That is a separate implementation; I'm not sure that they have full feature parity. We should probably create a transformer for both.

**Comment by calebeby** [comment]
@jescalan Are there any major differences between the two, enough that we should have two separate transformers?

**Comment by tunnckoCore** [comment]
@calebeby haha, thanks :D 

I believe we should have only one and it should be @reshape's because is by the original author.

> Are there any major differences between the two

It's possible.

**Comment by jescalan** [comment]
Yeah there are major differences, the two are not compatible. Reshape's version has accurate error messages and the infrastructure in place for source maps, and is actively maintained. The posthtml version currently is not as actively maintained at the moment. That being said, while I wrote them both, they are two separate implementations and would require different transformers if you wanted to support them both.

**Comment by calebeby** [comment]
:+1: for only reshape's

**Comment by calebeby** [comment]
https://github.com/jstransformers/jstransformer-sugarml
