### ISSUE TITLE
Rollup

### ISSUE THREAD

**Issue by calebeby** [jstransformers/jstransformer#179]
https://github.com/rollup/rollup

I figured... We have Browserify and webpack

**Comment by calebeby** [comment]
https://github.com/jstransformers/jstransformer-rollup

**Comment by tunnckoCore** [comment]
good catch but bad implementation

Just pass options both to `rollup.rollup(options)` then `bundle.generate(options)`. That's how I did it in [start-rollup](https://github.com/tunnckoCore/start-rollup/blob/master/index.js) and that's how Rollup's CLI is built.

**Comment by calebeby** [comment]
Sounds good. I'll do that
