### ISSUE TITLE
Problems with `.renderFileAsync`

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#18]
I dont know why, but for some reason it fails to populate template with given locals in some template engines like handlebars and I guess other was toffee. [check this](https://github.com/tunnckoCore/jstransformer-handlebars/blob/master/test/index.js#L82) and [this](https://github.com/jstransformers/jstransformer-toffee/blob/master/test/index.js#L83), its not logical to fail, because other render* methods works correctly.

For that reason Im so strong with my position to use `jstransformer` for testing it helps to find bugs like this, have more useful use cases which in other hand in one point is useful as examples.

**Comment by tunnckoCore** [comment]
Because I love (and not only me, ofc) to follow readmes and docs, but if they do not helps I go to the tests, if there's no tests or they are so ugly, Im forced to go to the source which is waste of time, then Im forced to follow the deps chain and etc and etc.

**Comment by tunnckoCore** [comment]
Need MOAR proof of #16 ? Please, try run `transform.compile`

```js
var hogan = require('jstransformer')(require('./index'));
var compiled = hogan.compile('<p>Hello, my name is {{name}}.</p>');
var result = compiled.fn({name: 'foobar'});

console.log(result);
```

mm?

**Comment by TimothyGu** [comment]
#19 fixes this by the way.

**Comment by TimothyGu** [comment]
@tunnckoCore, fixed: jstransformers/jstransformer-hogan@72b743e625ec79c7ddce1524a12885ffbf4663d6. I think you have a point on #16, but please discuss with @ForbesLindesay more on that topic on #16 before we can adopt a project-wide policy.

@hemanth See above commit. For later contributions please always make `compile()` self-contained. And when you get a chance please add me as owner and tag and publish v0.0.2. Thanks.

**Comment by tunnckoCore** [comment]
> @tunnckoCore, fixed: jstransformers/jstransformer-hogan@72b743e625ec79c7ddce1524a12885ffbf4663d6.

yea, just notice it. and #19 still not fixes this

**Comment by ForbesLindesay** [comment]
Fixing things like this belong in the jstransformer tests.  We know the tests for jstransformer are very incomplete, and that's why we haven't caught all the bugs yet.  **Please stop attempting to test jstransformer in the test suites for other libraries.**

**Comment by ForbesLindesay** [comment]
If you need more convincing, check out where the test coverage is currently lacking, relative to where you found a bug:

https://coveralls.io/builds/2333120/source?filename=index.js
