### ISSUE TITLE
Do not center the logo on README.md

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#21]
The centered logo distracts the user from the documentation, which is more important. Also looks weird on npm: https://www.npmjs.com/package/jstransformer

Let's do what Promises does for their logo:

https://github.com/then/promise

**Comment by tunnckoCore** [comment]
LOOOL, I didnt notice that in npm

:+1: 

or maybe separate readme for npm? mean.. when publish to npm just remove it, lol

**Comment by ForbesLindesay** [comment]
Separate readme's are a pretty big overhead.  I think we should just make the logo much smaller everywhere.  Unfortunately npmjs does not support image alignment, but it might be something that a pull request could fix.

**Comment by RyanZim** [comment]
@RobLoach Should this be closed due to the closing of #22?

**Comment by RobLoach** [comment]
@RyanZim Thanks for helping clean up the board!
