### ISSUE TITLE
blockml

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer#213]
[blockml](https://www.npmjs.com/package/blockml) is a markup language that generates HTML. The purpose of blockml is to make writing HTML feel more consistent with the way we write JavaScript and CSS.

https://medium.com/@ajmd17/how-i-built-my-own-react-in-two-days-and-why-i-did-it-969c3d048f78

**Comment by webketje** [comment]
Project looks abandoned. Bears similiarity to Pug, but never went past release 0.0.8-alpha and was last worked on in 2017
