### ISSUE TITLE
trademark/copyright issue on logo

### ISSUE THREAD

**Issue by AtlasJan** [jstransformers/jstransformer#221]
The 'autobot' portion of the logo used is a trademark registered to Hasbro, Inc. (US: [76673705](http://tarr.uspto.gov/servlet/tarr?regser=serial&entry=76673705http://tarr.uspto.gov/servlet/tarr?regser=serial&entry=76673705)), to avoid potential litigation/trademark issues, I feel as if the logo should be changed: as the [MIT License](https://opensource.org/licenses/MIT) implies copyright on the respected image, which may be a potential violation.

I personally don't think it's the best idea to have a giant, well-funded legal team descend unto this project, so I'd say "better safe than sorry".

**Comment by RobLoach** [comment]
Good call. I'm unsure if it would fall under fair use, and I'm also no copyright lawyer.

**Comment by ForbesLindesay** [comment]
I'd be happy to see a suggestion for an alternative. It personally hadn't occurred to me that there was a connection with that kind of transformer when I chose the project name. The type of transformer I had in mind was more like:

![440px-Transformer3d_col3 svg](https://user-images.githubusercontent.com/1260646/66662057-01933f00-ec40-11e9-8395-bc9cd22867f6.png)

The current logo does look cool though, so we'd need to find a good logo if we're going to replace it.

**Comment by AtlasJan** [comment]
Added an idea for a new logo: #225

**Comment by AtlasJan** [comment]
Could someone fix the README for me? That'd be appreciated.
