### ISSUE TITLE
Calling .compile() when .compile() doesn't exist

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#25]
When the transformer doesn't have `.compile()`, but does have `.render()`, `jstransformer.compile()` could create it.....

``` javascript
Transformer.prototype.compile = function (str, options) {
  if (!this.can('compile')) {
    // Fall back to tr.render(), if it's available.
    if (this.can('render')) {
      var _this = this;
      return tr.normalizeFn(function (locals) {
        return _this._tr.render(str, options, locals);
      });
    }
```

**Comment by ForbesLindesay** [comment]
Interesting idea.  Probably worth it but I initially didn't do it because I had some debate as to whether to do:

```js
if (this.can('render')) {
  var _this = this;
  return tr.normalizeFn(function (locals) {
    return _this.render(str, options, locals).body;
  });
}
```

or

```js
if (this.can('render')) {
  var result = this.render(str, options).body;
  return tr.normalizeFn(function (locals) {
    return result;
  });
}
```

I think you're probably right that the first option is better though.

P.S. we should also use the same techniques to extend compileFile, compileAsync and compileFileAsync.

**Comment by RobLoach** [comment]
Saw that Tim implemented render() due to this deficiency in [lodash's index.js](https://github.com/jstransformers/jstransformer-lodash/blob/master/index.js) .

**Comment by ForbesLindesay** [comment]
I'm confused.  This deficiency is the other way round.  That render method definitely shouldn't be necessary

**Comment by RobLoach** [comment]
> I'm confused. This deficiency is the other way round. That render method definitely shouldn't be necessary

Seems it is the other way around. Must have been thinking of something else. Either that, or it's one case where I found it weird to have both, and then saw why having both seemed like a good idea.

Either way, building .compile() seems like something JSTransformer should do when .render() is available.

**Comment by TimothyGu** [comment]
The point of a `compile()` function is that we can cache the function. This doesn't achieve that, but is the best thing to do, so a +1 from me.

@RobLoach said:
> Saw that Tim implemented render() due to this deficiency in [lodash's index.js](https://github.com/jstransformers/jstransformer-lodash/blob/master/index.js).

Huh? Don't think I ever touched lodash before…

**Comment by RobLoach** [comment]
> Huh? Don't think I ever touched lodash before…

Sorry, meant Tunnck. Busy day.

**Comment by tunnckoCore** [comment]
> the best thing to do when we want to ensure all jstransformers have a uniform API, so a +1 from me.

et al :+1:

**Comment by RobLoach** [comment]
https://github.com/jstransformers/jstransformer/issues/28
