### ISSUE TITLE
Add API docs for .compile()

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#26]

**Comment by tunnckoCore** [comment]
What's the idea behind `*Client*` methods?
It looks like that they should return string or object like `render*` methods should do, instead of function or object as in `compile*`.

What's the use cases?

**Comment by RyanZim** [comment]
@tunnckoCore `client` options or methods are included in some template engines that compile functions that can be run without depending on the template engine.

This means you can `.toString()` them and write them to a file. You can load this file in a browser (client) environment without loading the template engine and run them!

**Comment by RyanZim** [comment]
I'm working on this.
