### ISSUE TITLE
Normalize outputFormat of all the modules

### ISSUE THREAD

**Issue by TimothyGu** [jstransformers/jstransformer#3]
In transformers, `'xml'` is used, even for HTML output.

In the first few packages ported by @ForbesLindesay, they are marked as `'html'`.

In my first few packages, I used `'html'` as well, but then I saw that transformers was using `'xml'`, so I switched to `'xml'`.

What *exactly* should I use?

What about hybrids like XHTML/XML: https://github.com/jstransformers/jstransformer-cdata?

**Comment by ForbesLindesay** [comment]
`html`.  I think it's far more intuitive since almost all such modules are primarily outputting html.

**Comment by TimothyGu** [comment]
Done with a script:

```sh
for d in `ls -d */`; do
  echo $d
  cd $d
  if grep 'exports\.outputFormat.*xml' index.js; then
    vim -c '%s/xml/html/gc' -c 'wq' index.js
    grep version package.json
    read oldver
    read newver
    sedoldver=`printf $oldver | sed 's/\./\\./g'`
    sednewver=`printf $newver | sed 's/\./\\./g'`
    sed -i "s/$sedoldver/$sednewver/" package.json
    git add index.js
    git commit -m "Use \`'html'\` as output format" -m "Per jstransformers/jstransformer#3."
    vim History.md || bash
    git commit -a -m "$newver"
    git tag "v$newver"
    echo 'Last chance!'
    bash
    git push
    git push --tags
    npm publish
  fi
  cd ..
done
```
