### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#4]
Now that there are a good amount of Transformers available from #1, it is time to think about what the next steps are for JS Transformers' success. So, what is missing?

* Add an API to [jstransformer](https://github.com/jstransformers/jstransformer) that is rather similar to the existing implementation?
* Push a project page forwards to http://jstransformers.github.io ?
* Add API docs on the `.compile` function for templates?
* Create plugins for other systems that could use JS Transformers?
* Publish [jstransformer](https://github.com/jstransformers/jstransformer) on `npm`?

**Comment by TimothyGu** [comment]
@RobLoach said:

> * Add an API to [jstransformer](https://github.com/jstransformers/jstransformer) that is rather similar to the existing implementation?

It is similar to its predecessor [transformers](https://github.com/ForbesLindesay/transformers).

> * Add API docs on the `.compile` function for templates?

That is on my todo list but you can get started on it.

> * Create plugins for other systems that could use JS Transformers?

Jade is on our todo list.

> * Publish [jstransformer](https://github.com/jstransformers/jstransformer) on `npm`?

It is already.

**Comment by TimothyGu** [comment]
See npmjs.org/jstransformer

**Comment by ForbesLindesay** [comment]
Website wise I have jstransformers.org.  We should start a www repo and build a node.js website which I will host.  We can use jade to build the website, and automatically pull docs/readmes from all the other jstransformers repos on github.  We can also provide demos in the style of jsbin etc. via browserify (using www.brcdn.org)

**Comment by tunnckoCore** [comment]
@ForbesLindesay brcdn.org, looks awesome, good job!
