### ISSUE TITLE
Promise everything? Or Generators?

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#45]
Rather than returning the `{dependencies, body}` for `.render()` and `.renderFile()`, have it return a Promise?

Or switch over to Generators and `yield` for everything?

**Comment by TimothyGu** [comment]
Well, these methods are designed for synchronous consumption…

**Comment by ForbesLindesay** [comment]
Promises can only be consumed a synchronously.  Some of our transformers are asynchronous, but many are synchronous.  Some consumers (e.g. jade filters) are synchronous and can therefore only support the synchronous transformers.  They will use the synchronous `render` or `compile` APIs, but some consumers can handle asynchronous transformers, and should therefore use the `...Async` APIs
