### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#49]
http://leonidas.github.io/transparency/

**Comment by tunnckoCore** [comment]
jsdom fails... it looks like `0.10.0` not works, i will investigate

**Comment by tunnckoCore** [comment]
it seems all that stuff cant be done.

neither `jsdom` and `node-jsdom` and tweaks to the `transparancy` didn't work even on Travis.
https://travis-ci.org/chorks/transparency

**Comment by tunnckoCore** [comment]
or maybe try using virtual-dom? hm. i will try when i can. feel free to try.
