### ISSUE TITLE
Input Format

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer#5]
We have `outputFormat` to define what the outcome of the tranformer is. Should we also define an `inputFormat` to say what the input for the transformer usually is?

SCSS could become `scss`, defaulting from the `exports.name`.

While Remarkable, Marked, Markdown, etc would define:
``` javascript
exports.inputFormats = ['md', 'markdown'];
```

**Comment by TimothyGu** [comment]
The most significant difference of jstransformer versus transformers is that the user install whatever (s)he wants to use, and thus it is not necessary to use an input format but rather the name of transformer.

@ForbesLindesay might be able to provide more insights on this.

Also I don't see the point in `outputFormat` either.

**Comment by ForbesLindesay** [comment]
I think inputFormat might be a good idea.

Neither will be used by jade, but both could be useful for building static site generators and CLIs
